name: sistema-votacao
recipe: drupal10
config:
  webroot: web
  php: '8.3'

services:
  appserver:
    type: php:8.3
  database:
    type: mariadb:10.6

tooling:
  composer:
    service: appserver
  drush:
    service: appserver
